#!/usr/bin/env python3
"""
Add mythology and Shakespeare characters as instruction files.
Skips any that already exist.
"""

import json
import re
from pathlib import Path

INSTRUCTIONS_DIR = Path(__file__).parent.parent / "data" / "roles" / "instructions"

# New characters organized by source
NEW_CHARACTERS = {
    "Greek mythology": [
        "Hera",
        "Ares",
        "Apollo",
        "Artemis",
        "Hermes",
        "Hephaestus",
        "Demeter",
        "Dionysus",
        "Hestia",
        "Cronus",
        "Rhea",
        "Prometheus",
        "Atlas",
        "Hyperion",
        "Oceanus",
        "Tethys",
        "Themis",
        "Mnemosyne",
        "Iapetus",
        "Coeus",
        "Gaia",
        "Uranus",
        "Nyx",
        "Erebus",
        "Tartarus",
        "Eros",
        "Chaos",
        "Theseus",
        "Jason",
        "Bellerophon",
        "Atalanta",
        "Orpheus",
        "Eurydice",
        "Patroclus",
        "Ajax",
        "Diomedes",
        "Nestor",
        "Agamemnon",
        "Menelaus",
        "Helen of Troy",
        "Paris",
        "Priam",
        "Hecuba",
        "Cassandra",
        "Andromache",
        "Penelope",
        "Telemachus",
        "Circe",
        "Calypso",
        "Polyphemus",
        "Tiresias",
        "Antigone",
        "Oedipus",
        "Jocasta",
        "Creon",
        "Electra",
        "Orestes",
        "Clytemnestra",
        "Aegisthus",
        "Iphigenia",
        "Narcissus",
        "Echo",
        "Daedalus",
        "Icarus",
        "Minos",
        "Ariadne",
        "Phaedra",
        "Hippolytus",
        "Tantalus",
        "Sisyphus",
        "Ixion",
        "Pandora",
        "Pygmalion",
        "Galatea",
        "Arachne",
        "Niobe",
        "Cerberus",
        "Hydra",
        "Chimera",
        "Minotaur",
        "Scylla",
        "Charybdis",
        "Typhon",
        "Echidna",
        "Pegasus",
        "Centaur Chiron",
        "Siren",
        "Persephone",
        "Pan",
        "Nemesis",
        "Tyche",
        "Nike",
        "Hecate",
        "Eris",
        "Hypnos",
        "Thanatos",
        "Morpheus",
        "Asclepius",
        "Ganymede",
    ],
    "Norse mythology": [
        "Frigg",
        "Baldur",
        "Tyr",
        "Heimdall",
        "Bragi",
        "Idun",
        "Vidar",
        "Vali",
        "Forseti",
        "Hodr",
        "Hermod",
        "Sif",
        "Freya",
        "Freyr",
        "Njord",
        "Loki",
        "Fenrir",
        "Jormungandr",
        "Hel",
        "Surtr",
        "Ymir",
        "Thrym",
        "Skadi",
        "Angrboda",
        "Sigurd",
        "Brynhild",
        "Gudrun",
        "Ragnar Lothbrok",
        "Lagertha",
        "Bjorn Ironside",
        "Ivar the Boneless",
        "Erik the Red",
        "Leif Erikson",
        "Valkyrie",
        "Norns",
        "Urd",
        "Verdandi",
        "Skuld",
        "Mimir",
        "Aegir",
        "Ran",
        "Nidhogg",
        "Ratatoskr",
        "Hugin",
        "Munin",
        "Sleipnir",
        "Garm",
        "Fafnir",
        "Andvari",
        "Wayland the Smith",
        "Beowulf",
        "Grendel",
        "Grendel's Mother",
    ],
    "Egyptian mythology": [
        "Ra",
        "Osiris",
        "Isis",
        "Horus",
        "Set",
        "Anubis",
        "Thoth",
        "Hathor",
        "Bastet",
        "Sekhmet",
        "Ptah",
        "Atum",
        "Khnum",
        "Sobek",
        "Khonsu",
        "Nut",
        "Geb",
        "Shu",
        "Tefnut",
        "Nephthys",
        "Ma'at",
        "Bes",
        "Taweret",
        "Ammit",
        "Apep",
        "Serqet",
        "Neith",
        "Wadjet",
        "Nekhbet",
        "Min",
        "Montu",
        "Aten",
        "Amun",
        "Mut",
        "Khepri",
        "Seshat",
        "Imhotep",
        "Nefertiti",
        "Cleopatra",
        "Tutankhamun",
        "Ramesses II",
        "Khufu",
        "Akhenaten",
        "Hatshepsut",
    ],
    "Hindu mythology": [
        "Brahma",
        "Vishnu",
        "Shiva",
        "Rama",
        "Krishna",
        "Narasimha",
        "Vamana",
        "Parashurama",
        "Matsya",
        "Kurma",
        "Varaha",
        "Kalki",
        "Parvati",
        "Lakshmi",
        "Saraswati",
        "Durga",
        "Kali",
        "Sita",
        "Radha",
        "Ganga",
        "Yamuna",
        "Ganesha",
        "Hanuman",
        "Kartikeya",
        "Indra",
        "Surya",
        "Chandra",
        "Agni",
        "Vayu",
        "Varuna",
        "Yama",
        "Kubera",
        "Arjuna",
        "Bhima",
        "Yudhishthira",
        "Nakula",
        "Sahadeva",
        "Draupadi",
        "Karna",
        "Duryodhana",
        "Bhishma",
        "Drona",
        "Ashwatthama",
        "Shakuni",
        "Gandhari",
        "Kunti",
        "Abhimanyu",
        "Lakshmana",
        "Bharata",
        "Shatrughna",
        "Ravana",
        "Vibhishana",
        "Kumbhakarna",
        "Meghnad",
        "Mandodari",
        "Jatayu",
        "Sugriva",
        "Vali",
        "Angada",
        "Narada",
        "Vyasa",
        "Valmiki",
        "Vasishtha",
        "Vishwamitra",
        "Agastya",
        "Mahishasura",
        "Hiranyakashipu",
        "Prahlada",
        "Bali",
        "Garuda",
        "Nandi",
    ],
    "Chinese mythology": [
        "Jade Emperor",
        "Queen Mother of the West",
        "Erlang Shen",
        "Nezha",
        "Lei Gong",
        "Dian Mu",
        "Long Wang",
        "Ao Guang",
        "Guan Yu",
        "Zhong Kui",
        "Zao Jun",
        "Tu Di Gong",
        "Caishen",
        "Yue Lao",
        "Mazu",
        "Guanyin",
        "Lu Dongbin",
        "He Xiangu",
        "Zhang Guolao",
        "Lan Caihe",
        "Li Tieguai",
        "Han Xiangzi",
        "Cao Guojiu",
        "Zhongli Quan",
        "Sun Wukong",
        "Xuanzang",
        "Zhu Bajie",
        "Sha Wujing",
        "White Dragon Horse",
        "Bull Demon King",
        "Princess Iron Fan",
        "Red Boy",
        "White Bone Demon",
        "Liu Bei",
        "Zhang Fei",
        "Zhuge Liang",
        "Cao Cao",
        "Sun Quan",
        "Lu Bu",
        "Diao Chan",
        "Zhou Yu",
        "Sima Yi",
        "Jiang Ziya",
        "King Zhou",
        "Daji",
        "Pangu",
        "Nuwa",
        "Fuxi",
        "Shennong",
        "Yellow Emperor",
        "Chi You",
        "Yan Emperor",
        "Gonggong",
        "Zhu Rong",
        "Hou Yi",
        "Chang'e",
        "Wu Gang",
        "Cowherd",
        "Weaver Girl",
        "White Snake",
        "Green Snake",
        "Xu Xian",
        "Fahai",
        "Mulan",
        "Meng Jiangnu",
        "Liang Shanbo",
        "Zhu Yingtai",
        "Song Jiang",
        "Wu Song",
        "Lin Chong",
        "Lu Zhishen",
        "Li Kui",
        "Dragon",
        "Phoenix",
        "Qilin",
        "Pixiu",
        "Bai Ze",
    ],
    "Shakespeare": [
        "Hamlet",
        "Ophelia",
        "Claudius",
        "Gertrude",
        "Polonius",
        "Laertes",
        "Horatio",
        "Ghost of King Hamlet",
        "Rosencrantz",
        "Guildenstern",
        "Macbeth",
        "Lady Macbeth",
        "Banquo",
        "Macduff",
        "Lady Macduff",
        "Malcolm",
        "The Three Witches",
        "Duncan",
        "Othello",
        "Iago",
        "Desdemona",
        "Cassio",
        "Emilia",
        "Roderigo",
        "Brabantio",
        "King Lear",
        "Cordelia",
        "Goneril",
        "Regan",
        "Edmund",
        "Edgar",
        "Gloucester",
        "Kent",
        "The Fool",
        "Romeo",
        "Juliet",
        "Mercutio",
        "Tybalt",
        "Friar Lawrence",
        "The Nurse",
        "Benvolio",
        "Paris",
        "Capulet",
        "Lady Capulet",
        "Montague",
        "Julius Caesar",
        "Brutus",
        "Cassius",
        "Mark Antony",
        "Portia",
        "Calpurnia",
        "Octavius",
        "Cleopatra",
        "Enobarbus",
        "Prospero",
        "Ariel",
        "Caliban",
        "Miranda",
        "Ferdinand",
        "Puck",
        "Oberon",
        "Titania",
        "Bottom",
        "Hermia",
        "Lysander",
        "Helena",
        "Demetrius",
        "Theseus",
        "Hippolyta",
        "Viola",
        "Olivia",
        "Malvolio",
        "Sir Toby Belch",
        "Sir Andrew Aguecheek",
        "Feste",
        "Sebastian",
        "Maria",
        "Orsino",
        "Beatrice",
        "Benedick",
        "Hero",
        "Claudio",
        "Don John",
        "Dogberry",
        "Rosalind",
        "Orlando",
        "Touchstone",
        "Jaques",
        "Celia",
        "Duke Senior",
        "Shylock",
        "Bassanio",
        "Antonio",
        "Jessica",
        "Richard III",
        "Henry V",
        "Henry IV",
        "Prince Hal",
        "Falstaff",
        "Hotspur",
        "Richard II",
        "Kate",
        "Petruchio",
        "Leontes",
        "Hermione",
        "Perdita",
        "Isabella",
        "Angelo",
        "Titus Andronicus",
        "Tamora",
        "Aaron",
        "Lavinia",
        "Coriolanus",
        "Volumnia",
        "Timon",
    ],
}


def sanitize_filename(source: str, name: str) -> str:
    """Convert source + name to safe filename."""
    # Normalize source
    source_slug = source.lower().replace(" ", "_")

    # Normalize name
    name_slug = re.sub(r"[^\w\s-]", "", name)
    name_slug = re.sub(r"[-\s]+", "_", name_slug)
    name_slug = name_slug.lower().strip("_")

    return f"{source_slug}__{name_slug}.json"


def make_instruction(name: str, source: str) -> dict:
    """Create instruction file content."""
    return {
        "instruction": [
            {"pos": f"You are {name} from {source}. Respond as this character would."},
            {"pos": f"Embody {name} from {source}. Stay in character."},
            {"pos": f"You are roleplaying as {name} from {source}."},
            {"pos": f"Take on the persona of {name} from {source}."},
            {"pos": f"Act as {name} from {source}."},
        ]
    }


def main():
    INSTRUCTIONS_DIR.mkdir(parents=True, exist_ok=True)

    existing = set(f.stem for f in INSTRUCTIONS_DIR.glob("*.json"))

    added = 0
    skipped = 0

    for source, characters in NEW_CHARACTERS.items():
        print(f"\n{source}:")
        for name in characters:
            filename = sanitize_filename(source, name)
            stem = filename.replace(".json", "")

            if stem in existing:
                print(f"  [skip] {name}")
                skipped += 1
                continue

            content = make_instruction(name, source)
            output_path = INSTRUCTIONS_DIR / filename

            with open(output_path, "w") as f:
                json.dump(content, f, indent=2)

            print(f"  [add]  {name}")
            added += 1

    print(f"\n{'=' * 40}")
    print(f"Added: {added}")
    print(f"Skipped (already exist): {skipped}")
    print(f"Total instruction files: {len(list(INSTRUCTIONS_DIR.glob('*.json')))}")


if __name__ == "__main__":
    main()
